[build]
builder = "nixpacks"
buildCommand = "npm install --legacy-peer-deps --include=dev && ./node_modules/.bin/craco build"

[deploy]
startCommand = "npx serve -s build -l $PORT"
restartPolicyType = "on_failure"
